name = "pitiles"
compatibility_date = "2026-05-20"
main = "./src/worker.ts"

[[routes]]
pattern = "play-pi-tiles.com"
custom_domain = true

[[routes]]
pattern = "www.play-pi-tiles.com"
custom_domain = true

[assets]
directory = "./dist"
binding = "ASSETS"
headers = [
  { for = "/*", values = { X-Frame-Options = "ALLOWALL" } }
]

[[secrets_store_secrets]]
binding = "PI_API_KEY"
store_id = "718e22e76df5429d902853d6d9473603"
secret_name = "PI_API_KEY"

[[secrets_store_secrets]]
binding = "PI_SERVER_API_KEY"
store_id = "718e22e76df5429d902853d6d9473603"
secret_name = "PI_SERVER_API_KEY"
