name = "pitiles"
compatibility_date = "2026-05-20"
main = "./src/worker.ts"
workers_dev = true
preview_urls = true

[[routes]]
pattern = "play-pi-tiles.com"
custom_domain = true

[[routes]]
pattern = "www.play-pi-tiles.com"
custom_domain = true

[assets]
directory = "./dist"
binding = "ASSETS"
headers = [
  { for = "/*", values = { X-Frame-Options = "ALLOWALL" } }
]

[[kv_namespaces]]
binding = "LEADERBOARD"
id = "11592418f95e4421bbc2d37bc9c910ec"
